credentials:
  usernames:
    felipe:
      email: felipe@beanalytic.com.br
      name: Felipe Lisboa
      password: '123' # To be replaced with hashed password
    marconi:
      email: marconi@beanalytic.com.br
      name: Marconi Medeiros
      password: '123' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - felipe@beanalytic.com.br